site_name: Rick
site_description: Python plumbing for micro-framework based applications
strict: true
site_url: https://git.oddbit.org/OddBit/rick
repo_name: OddBit/rick
repo_url: https://git.oddbit.org/OddBit/rick

theme:
  name: material

nav:
- Overview: index.md
- Requests: 'forms/requests.md'
- Forms:
  - Overview: 'forms/index.md'
  - Form Class: 'forms/form.class.md'
- Validators:
  - Overview: 'validators/index.md'
  - Available Validators: 'validators/validator_list.md'
- Serializers:
  - Overview: 'serializers/index.md'
  - JSON Serializer: 'serializers/json.md'
  - MessagePack Serializer: 'serializers/msgpack.md'
- Resources:
  - Overview: 'resources/index.md'
  - Redis Cache: 'resources/redis.md'
  - Configuration: 'resources/config.md'
  - Console Output: 'resources/console.md'
- Mixins:
    - Translation: 'mixins/translator.class.md'

plugins:
- search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


