site_name: Rick
site_description: Python plumbing for micro-framework based applications
strict: true
site_url: https://github.com/oddbit-project/rick
repo_name: oddbit-project/rick
repo_url: https://github.com/oddbit-project/rick

theme:
  name: material

nav:
- Overview: index.md
- Forms:
  - Overview: 'forms/index.md'
  - RequestRecord: 'forms/requests.md'
  - Form Class: 'forms/form.class.md'
  - Error Format: 'forms/errors.md'
- Validators:
  - Overview: 'validators/index.md'
  - Available Validators: 'validators/validator_list.md'
- Serializers:
  - Overview: 'serializers/index.md'
  - JSON Serializer: 'serializers/json.md'
  - MessagePack Serializer: 'serializers/msgpack.md'
- Resources:
  - Overview: 'resources/index.md'
  - Redis Cache: 'resources/redis.md'
  - Configuration: 'resources/config.md'
  - File Operations: 'resources/file.md'
  - Stream Processing: 'resources/stream.md'
  - Console Output: 'resources/console.md'
- Cryptography:
  - Overview: 'crypto/index.md'
  - Fernet256 Encryption: 'crypto/fernet256.md'
  - Bcrypt Password Hashing: 'crypto/bcrypt.md'
  - Buffer Hashing: 'crypto/buffer.md'
- Mixins:
    - Translation: 'mixins/translator.class.md'

plugins:
- search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


